clear
format long
global sigma  r  N
sigma=zeros(1,11); r=zeros(1,2);N=zeros(1,2);
 J=2;

ObjectiveFunction = @simple_fit;
nvars = 15;
LB = zeros(1,nvars);
A=zeros(nvars);
UB = [];
X=zeros(nvars+1,Final)';
tic
for i = 1: 100
    options = gaoptimset(       'Generations', 5000, ...
        'PopulationSize', 600, ...
        'StallGenLimit', 100, ...
        'TolFun', 1e-6, ...
        'UseParallel', true, ...
        'Vectorized', 'off', ...
        'CrossoverFraction', 0.85, ...
        'EliteCount', 5, ...
        'FitnessLimit', -Inf, ...
        'MutationFcn',{@mutationadaptfeasible,0.1}, ...
        'SelectionFcn', @selectiontournament);
    [x,fval] = ga (ObjectiveFunction, nvars ,[],[],[],[],LB,UB,[],options);
    X(i,:)=[x,fval];
    disp(X(i,:)')
end
toc

save([num2str(J) 'X.mat'], 'X')